// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdBXMMkep3JuwoElcJOlyhYlkw175bJo8',
    appId: '1:823754601413:web:7f2e9351324518766ad1ac',
    messagingSenderId: '823754601413',
    projectId: 'promorey-a59ca',
    authDomain: 'promorey-a59ca.firebaseapp.com',
    storageBucket: 'promorey-a59ca.firebasestorage.app',
    measurementId: 'G-THVLBQXWC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXRZgH6lw_VMcgQMjDsUuukeBy2meujA',
    appId: '1:823754601413:android:329e9a64656315e66ad1ac',
    messagingSenderId: '823754601413',
    projectId: 'promorey-a59ca',
    storageBucket: 'promorey-a59ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQaKSLeunZRQgjoPRju8dFOS4MocosLuM',
    appId: '1:823754601413:ios:24c1e180dc1fbf7e6ad1ac',
    messagingSenderId: '823754601413',
    projectId: 'promorey-a59ca',
    storageBucket: 'promorey-a59ca.firebasestorage.app',
    iosBundleId: 'com.example.promorey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQaKSLeunZRQgjoPRju8dFOS4MocosLuM',
    appId: '1:823754601413:ios:24c1e180dc1fbf7e6ad1ac',
    messagingSenderId: '823754601413',
    projectId: 'promorey-a59ca',
    storageBucket: 'promorey-a59ca.firebasestorage.app',
    iosBundleId: 'com.example.promorey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdBXMMkep3JuwoElcJOlyhYlkw175bJo8',
    appId: '1:823754601413:web:cb7f49aae7a0480e6ad1ac',
    messagingSenderId: '823754601413',
    projectId: 'promorey-a59ca',
    authDomain: 'promorey-a59ca.firebaseapp.com',
    storageBucket: 'promorey-a59ca.firebasestorage.app',
    measurementId: 'G-884S99VSRE',
  );
}
